// ---------------------------------------------------------
// Config
// ---------------------------------------------------------

var fieldName = {
    "title": "Study Title",
    "authors": "Authors",
    "study_type": "Study Type",
    "arm_efficacy_metric": "Efficacy Metric",
    "arm_efficacy_results": "Efficacy Results",
    "arm_description-1": "Arm Description 1",
    "arm_dosage-1": "Arm Dosage 1",
    "arm_description-2": "Arm Description 2",
    "arm_dosage-2": "Arm Dosage 2",
    "arm_description-3": "Arm Description 3",
    "arm_dosage-3": "Arm Dosage 3",
    "arm_description-4": "Arm Description 4",
    "arm_dosage-4": "Arm Dosage 4",
    "arm_description-5": "Arm Description 5",
    "arm_dosage-5": "Arm Dosage 5",
    "arm_description-6": "Arm Description 6",
    "arm_dosage-6": "Arm Dosage 6",
}
var shortName = {
    "title": "Study Title",
    "authors": "Authors",
    "study_type": "Study Type",
    "arm_efficacy_metric": "Efficacy Metric",
    "arm_efficacy_results": "Efficacy Results",
    "arm_description-1": "Arm Description 1",
    "arm_dosage-1": "Arm Dosage 1",
    "arm_description-2": "Arm Description 2",
    "arm_dosage-2": "Arm Dosage 2",
    "arm_description-3": "Arm Description 3",
    "arm_dosage-3": "Arm Dosage 3",
    "arm_description-4": "Arm Description 4",
    "arm_dosage-4": "Arm Dosage 4",
    "arm_description-5": "Arm Description 5",
    "arm_dosage-5": "Arm Dosage 5",
    "arm_description-6": "Arm Description 6",
    "arm_dosage-6": "Arm Dosage 6",
}
var longDesc = {
    "title": "Study Title",
    "authors": "Authors",
    "study_type": "Study Type",
    "arm_efficacy_metric": "Efficacy Metric",
    "arm_efficacy_results": "Efficacy Results",
    "arm_description-1": "Arm Description 1",
    "arm_dosage-1": "Arm Dosage 1",
    "arm_description-2": "Arm Description 2",
    "arm_dosage-2": "Arm Dosage 2",
    "arm_description-3": "Arm Description 3",
    "arm_dosage-3": "Arm Dosage 3",
    "arm_description-4": "Arm Description 4",
    "arm_dosage-4": "Arm Dosage 4",
    "arm_description-5": "Arm Description 5",
    "arm_dosage-5": "Arm Dosage 5",
    "arm_description-6": "Arm Description 6",
    "arm_dosage-6": "Arm Dosage 6",
}
var shortcutKey = {
    "title": "Study Title",
    "authors": "Authors",
    "study_type": "Study Type",
    "arm_efficacy_metric": "Efficacy Metric",
    "arm_efficacy_results": "Efficacy Results",
    "arm_description-1": "Arm Description 1",
    "arm_dosage-1": "Arm Dosage 1",
    "arm_description-2": "Arm Description 2",
    "arm_dosage-2": "Arm Dosage 2",
    "arm_description-3": "Arm Description 3",
    "arm_dosage-3": "Arm Dosage 3",
    "arm_description-4": "Arm Description 4",
    "arm_dosage-4": "Arm Dosage 4",
    "arm_description-5": "Arm Description 5",
    "arm_dosage-5": "Arm Dosage 5",
    "arm_description-6": "Arm Description 6",
    "arm_dosage-6": "Arm Dosage 6",
}

